config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  unauthenticated do
    root to: 'home#index'
  end

  authenticated do
    root 'restaurants#index'
  end

  resources :restaurants, only: %i[index show]
  resources :orders, only: %i[index show edit update]
  resources :order_items, only: %i[create update delete]
  resource :profile, only: %i[show update], controller: :profile
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  validates :name, uniqueness: { scope: :country }
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :restaurant
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy

  enum status: %i[cart pending complete]
  enum category: %i[visit delivery]
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  before_save :calculate_subtotal

  private

  def calculate_subtotal
    self.subtotal = quantity * item.cost
  end
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  belongs_to :city
  has_many :items
  has_many :orders
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :orders
  has_one :address, as: :addressable

  accepts_nested_attributes_for :address

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def home; end
end

app/controllers/order_items_controller.rb
# frozen_string_literal: true

class OrderItemsController < ApplicationController
  expose :order_item
  expose :order, -> { Order.where(user_id: current_user.id, restaurant_id: restaurant.id, status: 'cart').first_or_create }
  expose :item, id: ->{ params.dig(:order_item, :item_id) || params[:id] }
  expose :restaurant, from: :item

  def create
    order.order_items.create(order_item_params)
    flash[:notice] = "Item has been added to cart"
    redirect_to restaurant
  end

  def update
    order_item.update(order_item_params)
    flash[:notice] = "Item quantity has been updated"
    redirect_to edit_order_path(order)
  end

  private

  def order_item_params
    params.require(:order_item).permit(:item_id, :quantity)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  expose :order
  expose :orders, from: :current_user
  expose :restaurant, from: :order
  expose :order_items, from: :order

  def update
    order.update(order_params)
    flash[:notice] = "Order has been submit"
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:visit_at, :status, :category)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    current_user.build_address unless current_user.address
  end

  def update
    current_user.update(user_params)
    flash[:notice] = "Profile has been updated"
    redirect_to profile_path
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :email,
                                 :first_name, :last_name, :phone_number,
                                 address_attributes: %i[id street city_id notes phone_number])
  end
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  before_action :authenticate_user!

  expose :restaurants, -> { Restaurant.all }
  expose :restaurant
  expose :items, from: :restaurant
  expose :order, -> { Order.find_by(user_id: current_user.id, restaurant_id: restaurant.id, status: 'cart') }
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/order_items_helper.rb
# frozen_string_literal: true

module OrderItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/views/home/index.slim
h1 RestaurantApp
div = link_to 'Sign In', new_user_session_url
div = link_to 'Sign Up', new_user_registration_url

app/views/items/_item.slim
.card.p-3.mb-3
  .card-body
    = simple_form_for :order_item, url: order_items_path do |f|
      = f.input :item_id, as: :hidden, input_html: { value: item.id }
      .container.row
        .col-8
          h3.card-title = item.name
          .card-text = item.description
        .col-2
            = f.input :quantity, as: :integer
        .col-2
            = f.submit 'Add to cart', class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title RestaurantApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .d-flex.justify-content-center
      .w-50
        - if notice
          p.alert.alert-success= notice
        - if alert
          p.alert.alert-danger= alert
        = yield

app/views/order_items/_order_item.slim
.card.p-3.mb-3
  .card-body
    = simple_form_for order_item, url: order_item_url(order_item) do |f|
      = f.input :item_id, as: :hidden, input_html: { value: order_item.item_id }
      .container.row
        .col-3
          h3.card-title = order_item.item.name
        h3.col-3= "Subtotal: #{order_item.subtotal}"
        - if order.cart?
          .col-3
            = f.input :quantity, as: :integer
          .col-3
            = f.submit 'Update Quantity', class: 'btn btn-primary'
        - else
          .col-3
          .col-3
            h3.mt-3= "Quantity: #{order_item.quantity}"

app/views/orders/_order.slim
.card.p-3.mb-3
  .card-body
    .container.row
      .col-3
        h3.card-title = order.restaurant.name
        .card-text = order.visit_at
      .col-3
        h4.mt-3= "Total Price: #{order.order_items.sum(:subtotal)}"
      .col-2
        h4.mt-3 = order.status.titleize
      .col-2
        h4.mt-3 = order.category.titleize
      .col-2 = link_to 'Show Order', order

app/views/orders/edit.slim
h3.mb-3 = link_to 'Back', restaurants_url
h3.mb-3 = link_to "Order For #{restaurant.name}", restaurant

- if order.cart?
  = render order_items
  .card.p-3.mb-3
    .card-body
      = simple_form_for order, url: order_url(order) do |f|
        .container.row
          h3.card-title Order Info
          .card-body
            .mb-3 = f.input :category, collection: Order.categories.keys, label: 'Order Type', label_method: :titleize, include_blank: false
            .mb-3 = f.input :visit_at
            h4.mt-3 = "Total Price: #{order_items.sum(:subtotal)}"
            = f.input :status, as: :hidden, input_html: { value: :pending }
            = f.submit 'Submit', class: 'btn btn-primary mt-3'

app/views/orders/index.slim
.d-flex.justify-content-between
  h1 Your Orders
  h1= link_to 'Back', profile_url
= render orders

app/views/orders/show.slim
h3.mb-3 = link_to 'Back', orders_path
h3.mb-3 = link_to "Order For #{restaurant.name}", restaurant

= render order_items
.card.p-3.mb-3
  .card-body
      .container.row
        h3.card-title Order Info
        .card-body= order.visit_at
        h4.mt-3= "Total Price: #{order_items.sum(:subtotal)}"

app/views/restaurants/_restaurant.slim
.card.p-3.mb-3
  .card-body
    h3.card-title = restaurant.name
    .card-text = restaurant.description
    = link_to 'Show', restaurant_url(restaurant), class: 'btn btn-primary mt-3'

app/views/restaurants/index.html.slim
.d-flex.justify-content-between
  h1 Restaurants
  h1= link_to 'Your profile', profile_url
= render restaurants

app/views/restaurants/show.slim
h3.mb-5= link_to 'Back', restaurants_url
h3.mb-5= link_to 'Check your cart', edit_order_url(order.id) if order
.card.p-3.mb-3
  .card-body
    h3.card-title = restaurant.name
    .card-text = restaurant.description
h4 Items
= render items